name: Build and Deploy 🕛
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BASE: /${GITHUB_REPOSITORY#*/}/

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3.5.3

      - name: Pnpm 🧱
        uses: pnpm/action-setup@v2.2.4

      - name: Node.js ⚓
        uses: actions/setup-node@v3.6.0
        with:
          node-version: latest
          cache: pnpm

      - name: Install 🔧
        run: |
          pnpm i
          pnpm build
          touch dist/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.2
        if: github.ref_name == 'main'
        with:
          folder: dist
